### ISSUE TITLE
Timer update behavior on mouse move 

### ISSUE THREAD

**Issue by jsgit21** [johnvictorfs/escape-crystal-runelite-plugin#10]
I noticed if you are constantly moving the mouse the timer continues to count down until the mouse stops, which is when it recognizes the client interaction and resets the timer. Is there any particular reason why the timer only resets after mouse stops instead of while moving? I am curious if there's a technical limitation or if checking to reset the timer constantly while the mouse is moving might cause unstable performance?

**Comment by jsgit21** [comment]
Fantastic plugin, by the way!

**Comment by johnvictorfs** [comment]
This is most likely just a bug, I just copied how some other plugins checked for activity and haven't looked much into it, but I might revisit it

**Comment by jsgit21** [comment]
Would love to see it revisited, I know that "Escape Crystal Notify" correctly updates the time as the mouse is moved but I really like your implementation.

**Comment by johnvictorfs** [comment]
Fixed but not live yet, will comment again once the plugin has a new release
