### ISSUE TITLE
Should work when equipped too

### ISSUE THREAD

**Issue by MarcusOtter** [johnvictorfs/escape-crystal-runelite-plugin#8]
It would be nice to see the auto-tele timer count down when the crystal is equipped too. That way I can use it as a ring of life and save an inventory slot (but still be reminded that I have auto-tele on). The active/inactive text would be neat to see in the equipment tab too

**Comment by johnvictorfs** [comment]
I believe the auto-teleport function does not work when the crystal is equipped to be used a ring of life, but I could be wrong? I never actually tested it.

[https://oldschool.runescape.wiki/w/Escape_crystal](https://oldschool.runescape.wiki/w/Escape_crystal#:~:text=The%20crystal%20can%20also%20be%20equipped%20and%20toggled%20to%20act%20in%20the%20same%20manner%20as%20a%20ring%20of%20life%2C%20although%20this%20will%20cause%20the%20crystal%20to%20be%20unable%20to%20teleport%20out%20from%20the%20aforementioned%20activities%2C%20so%20players%20must%20have%20it%20unequipped%20should%20they%20wish%20to%20be%20able%20to%20do%20so%20in%20those%20activities.)

> The crystal can also be equipped and toggled to act in the same manner as a [ring of life](https://oldschool.runescape.wiki/w/Ring_of_life), although this will cause the crystal to be unable to teleport out from the aforementioned activities, so players must have it unequipped should they wish to be able to do so in those activities.

**Comment by ZephORSC** [comment]
The escape will act as both a ring of life and an escape crystal while equipped, at least while doing pvm outside of the listed activities on the wiki (Barbarian Assault, CoX, etc). Have not tested exactly what happens in those activities. Said feature has cost me over a million gold from afking too long.

**Comment by MarcusOtter** [comment]
Yep, it definitely works when equipped! That has also cost me 1M+

**Comment by johnvictorfs** [comment]
Oh that's interesting, I will look into changing that then
